"""add_private_dm_support

Revision ID: 08a3f0a2ceee
Revises: 82a5d82a3e77
Create Date: 2026-05-19 15:21:12.679646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '08a3f0a2ceee'
down_revision: Union[str, Sequence[str], None] = '82a5d82a3e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'account_id', name='uq_projectmember_project_account')
    )
    op.create_index(op.f('ix_projectmember_account_id'), 'projectmember', ['account_id'], unique=False)
    op.create_index(op.f('ix_projectmember_project_id'), 'projectmember', ['project_id'], unique=False)
    op.add_column('project', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('project', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_project_type'), 'project', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_type'), table_name='project')
    op.drop_column('project', 'is_private')
    op.drop_column('project', 'type')
    op.drop_index(op.f('ix_projectmember_project_id'), table_name='projectmember')
    op.drop_index(op.f('ix_projectmember_account_id'), table_name='projectmember')
    op.drop_table('projectmember')
    # ### end Alembic commands ###
