"""Add reactions, is_pinned, is_edited

Revision ID: 6e0eb9c3629f
Revises: ee4f6ddb89d6
Create Date: 2026-05-21 20:11:28.510289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6e0eb9c3629f'
down_revision: Union[str, Sequence[str], None] = 'ee4f6ddb89d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledmessage_account_id'), 'scheduledmessage', ['account_id'], unique=False)
    op.create_index(op.f('ix_scheduledmessage_is_sent'), 'scheduledmessage', ['is_sent'], unique=False)
    op.create_index(op.f('ix_scheduledmessage_project_id'), 'scheduledmessage', ['project_id'], unique=False)
    op.create_index(op.f('ix_scheduledmessage_scheduled_for'), 'scheduledmessage', ['scheduled_for'], unique=False)
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_account_id'), 'reaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_reaction_message_id'), 'reaction', ['message_id'], unique=False)
    op.add_column('message', sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('message', sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_edited')
    op.drop_column('message', 'is_pinned')
    op.drop_index(op.f('ix_reaction_message_id'), table_name='reaction')
    op.drop_index(op.f('ix_reaction_account_id'), table_name='reaction')
    op.drop_table('reaction')
    op.drop_index(op.f('ix_scheduledmessage_scheduled_for'), table_name='scheduledmessage')
    op.drop_index(op.f('ix_scheduledmessage_project_id'), table_name='scheduledmessage')
    op.drop_index(op.f('ix_scheduledmessage_is_sent'), table_name='scheduledmessage')
    op.drop_index(op.f('ix_scheduledmessage_account_id'), table_name='scheduledmessage')
    op.drop_table('scheduledmessage')
    # ### end Alembic commands ###
