"""add_name_to_account

Revision ID: c42bcf29830b
Revises: 7f51cf5d44e0
Create Date: 2026-05-12 15:01:19.804406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c42bcf29830b'
down_revision: Union[str, Sequence[str], None] = '7f51cf5d44e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add name column with a temporary server_default so Postgres can backfill
    # any existing rows (table may not be empty). The default is removed after
    # so that the application must always provide a real name on insert.
    op.add_column(
        'account',
        sa.Column(
            'name',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='',   # allows backfilling existing rows
        ),
    )
    # Remove the server default — from here on, the app supplies the name
    op.alter_column('account', 'name', server_default=None)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_column('account', 'name')
    # ### end Alembic commands ###
