"""add parent_id to message

Revision ID: cbbb1c8ed205
Revises: 6e0eb9c3629f
Create Date: 2026-05-23 16:27:06.103856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cbbb1c8ed205'
down_revision: Union[str, Sequence[str], None] = '6e0eb9c3629f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_parent_id'), 'message', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'message', 'message', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_index(op.f('ix_message_parent_id'), table_name='message')
    op.drop_column('message', 'parent_id')
    # ### end Alembic commands ###
