"""Add file_url and file_type to Message

Revision ID: ee4f6ddb89d6
Revises: e375f964be19
Create Date: 2026-05-20 22:31:01.143095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ee4f6ddb89d6'
down_revision: Union[str, Sequence[str], None] = 'e375f964be19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('message', sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'file_type')
    op.drop_column('message', 'file_url')
    # ### end Alembic commands ###
